=head1 Upgrading to METAMOD 2.13 from 2.12

=head2 PostgreSQL 9.1

METAMOD now supports initializing databases on servers running PostgreSQL 9.1.
Previous versions only supported running v.9 clients against v.8 servers.

Support for PostgreSQL 8.2 and earlier have been disabled to avoid unneccessary errors,
but may be reenabled by editing F<base/init/createdb.sh> (ca. line 80).

=head2 Dependency libraries

Metamod now contains all necessary Perl dependencies in the Debian package.

If installing from source, you must build the necessary Perl modulues using Carton.
Unfortunately Carton is currently in heavy development and not available on CPAN in
a usable version. Instead download and install the latest version from
L<http://search.cpan.org/dist/carton/> using F<cpanm> or whatever.
Then install the dependencies like this:

  $ cd ~/metamod/trunk
  $ carton install --deployment

You must also set your PERL5LIB to point to F<metamod/trunk/local/lib> in your environment,
or change CATALYST_LIB in master_config (defaults to the Debian install directory):

  CATALYST_LIB = /opt/metno-metamod-2.13/local/lib/perl5

=head2 WMS configuration settings

=head3 WMS background map configuration

The WMS background map configuration, which due to technical difficulties was hardcoded in earlier versions
have now been moved to master_config.

The following directives have been deprecated:

=over 4

=item WMS_BACKGROUND_MAPSERVER

=item WMS_NORTHPOLE_MAP

=item WMS_SOUTHPOLE_MAP

=item WMS_WORLD_MAP

=back

Instead the URLs must now be specified in master_config under WMS_MAPS for each desired projection:

  WMS_MAPS =
      'EPSG:4326'  'http://wms.example.com/maps/world.map'
      'EPSG:32661' 'http://wms.example.com/maps/northpole.map'
      'EPSG:32761' 'http://wms.example.com/maps/southpole.map'
      'EPSG:3995'  "http://wms.example.com/maps/northpole.map"
      'EPSG:3031'  "http://wms.example.com/maps/southpole.map"

If WMS_MAPS is not defined, it will fall back to using the deprecated directives listed previously.

Names and bounding boxes are defined in default_config.txt under WMS_PROJECTIONS and WMS_BOUNDING_BOXES,
but may be overridden in master_config.

=head3 Dynamic map search

The static maps in the search interface for the non-standard projections EPSG:93031 and 93995
have now been deprecated, in favour of dynamic WMS maps. These will automatically be enabled
if any of your search projections (defined in SRID_ID_COLUMNS) have a corresponding
URL defined in WMS_MAPS as described above. From 2.13 the default SRID_ID_COLUMNS is:

  SRID_ID_COLUMNS = 93995 93031 3995 3031 4326

B<NB:> To enable new SRIDs you need to re-initialize the metadata database and re-import all datasets
(preferably by running F<create_and_load_all.sh>). Also make sure the new SRIDs are supported
in your current version of PostGIS:

  # select auth_srid from spatial_ref_sys where auth_name='EPSG' and auth_srid in(3995, 3031, 4326);
   auth_srid
  -----------
        4326
        3031
        3995
  (3 rows)

Also note that since it is not possible to mix static and dynamic maps (and the previous projections
(EPSG:93031 and 93995) are difficult to support in WMS) you must set up WMS maps for all the SRIDS you
want to support searching in. Existing stored searches (as in Subscriptions) will continue to run as long
as the projections are included in SRID_ID_COLUMNS, but they cannot be edited.

