=head1 Upgrading to METAMOD 2.13 from 2.12

=head2 PostgreSQL 9.1

METAMOD now supports initializing databases on servers running PostgreSQL 9.1.
Previous versions only supported running v.9 clients against v.8 servers.

Support for PostgreSQL 8.2 and earlier have been disabled to avoid unneccessary errors,
but may be reenabled by editing F<base/init/createdb.sh> (ca. line 80).

=head2 Dependency libraries

Metamod now contains all necessary Perl dependencies included in the Debian package.
The previous F<metno-perl-webdev-ver1> package will no longer work since METAMOD 2.13
now requires Catalyst 5.9.

If installing from source, you must build the necessary Perl modules yourself,
preferably in a local lib using Carton. See L<Installation|../installation> for details.

=head2 Static files

Serving of static files via Apache has been re-enabled. Apache now looks for each file
first in the custom/static application directory, defaulting if not present to the installation directory.
B<Note that mod_rewrite now must be enabled in Apache for METAMOD to function correctly.>

  $ sudo a2enmod rewrite
  $ sudo service apache restart

=head2 Configuration

=head3 lsconf

A new utility C<lsconf> has been added to check current configuration settings:

  $ ./lsconf [--config <config file or dir>] [--split] [<variable>]

=head3 Deprecated configuration settings

The following directives have been deprecated and should be removed from F<master_config.txt> (they are
now defined in F<default_config.txt> and only used in case C<WMS_MAPS> should happen to be unset):

=over 4

=item WMS_BACKGROUND_MAPSERVER

=item WMS_NORTHPOLE_MAP

=item WMS_SOUTHPOLE_MAP

=item WMS_WORLD_MAP

=back

In addition, C<CATALYST_LIB> is now automatically computed and should be unset in F<master_config.txt>,
unless your dependencies are located somewhere else than in the METAMOD tree.

=head2 New WMS features

=head3 WMS background maps

The WMS background map configuration, which due to technical difficulties was hardcoded in earlier versions
is now fully configurable. In addition, several WMS maps have been made available as a public service and
are ready configured in F<default_config.txt>:

  WMS_MAPS =
      EPSG:32661  http://public-wms.met.no/backgroundmaps/northpole.map
      EPSG:32761  http://public-wms.met.no/backgroundmaps/southpole.map
      EPSG:4326   http://public-wms.met.no/backgroundmaps/world.map
      EPSG:3408   http://public-wms.met.no/backgroundmaps/northpole.map
      EPSG:3409   http://public-wms.met.no/backgroundmaps/southpole.map
      EPSG:3410   http://public-wms.met.no/backgroundmaps/world.map
      EPSG:3411   http://public-wms.met.no/backgroundmaps/northpole.map
      EPSG:3412   http://public-wms.met.no/backgroundmaps/southpole.map
      EPSG:3413   http://public-wms.met.no/backgroundmaps/northpole.map
      EPSG:3995   http://public-wms.met.no/backgroundmaps/northpole.map
      EPSG:3031   http://public-wms.met.no/backgroundmaps/southpole.map
      EPSG:32633  http://public-wms.met.no/backgroundmaps/world.map

To replace or extend this list, copy the whole directive to F<master_config.txt> and edit as desired.

Names and bounding boxes are also defined in F<default_config.txt> under C<WMS_PROJECTIONS> and C<WMS_BOUNDING_BOXES>,
but may be overridden in F<master_config.txt>.

=head3 Dynamic map search

The static maps in the search interface for the non-standard projections EPSG:93031 and 93995
have now been deprecated, in favour of dynamic WMS maps. These will automatically be enabled
if any of your search projections (defined in C<SRID_ID_COLUMNS>) have a corresponding
URL defined in C<WMS_MAPS> as described above.

From 2.13 the default C<SRID_ID_COLUMNS> are:

  SRID_ID_COLUMNS = 93995 93031 3995 3031 4326

The first two are only used for stored searches. The last three
are available for dynamic map search using the maps at public-wms.met.no.

To enable new SRIDs you need to re-initialize the metadata database and
re-import all datasets (preferably by running C<base/init/create_and_load_all.sh>).
B<Make sure to remove/edit any C<SRID_ID_COLUMNS> in F<master_config.txt> so it doesn't
override the default configuration.>

Since it is not possible to mix static and dynamic maps (and the
previous projections EPSG:93031 and 93995 are difficult to support in WMS) you
must set up WMS maps for all the additional SRIDS you want to support searching
in. Existing stored searches (as in Subscriptions) will continue to run as long
as the projections are included in C<SRID_ID_COLUMNS>, but they cannot be edited.

=head4 Running under older PostgreSQL version (8.x)

WMS map search is officially only supported using PostgreSQL 9.x. For older versions,
make sure the new SRIDs are supported in your current version of PostGIS:

  # select auth_srid from spatial_ref_sys where auth_name='EPSG' and auth_srid in(3995, 3031, 4326);
   auth_srid
  -----------
        4326
        3031
        3995
  (3 rows)

In case any of these projections are missing you must either install support for
them using data from L<spatialreference.org|http://spatialreference.org/> or remove them from
C<SRID_ID_COLUMNS>, otherwise C<create_and_load_all.sh> will probably fail.

=head2 Validation of ISO 19139/19115 documents in OAI-PMH

Due to a bug in libxml2 2.7.8 and earlier, validation of ISO files is not possible and has been disabled in METAMOD.
To enable this under Precise you need to compile 2.9.1 from source and install in a custom location:

  $ wget ftp://xmlsoft.org/libxml2/libxml2-2.9.1.tar.gz
  $ tar xfvz libxml2-2.9.1.tar.gz
  $ cd libxml2-2.9.1/
  $ ./configure --prefix=/opt/local --without-python
  $ make && sudo make install

After this is done you can add an external validation script in master_config:

PMH_LOCAL_VALIDATION =
    iso19115  '/opt/local/bin/xmllint --noout --schema [SCHEMA] [FILE]'
    iso19139  '/opt/local/bin/xmllint --noout --schema [SCHEMA] [FILE]'

From Ubuntu 14.4, ISO validation will be handled normally in METAMOD without the need for external validators.
