=head1 Deploying METAMOD

=head2 Introduction

This document assumes that the basic METAMOD software are working on the various servers where METAMOD
are intended to run.  How to achieve this is described in a separate document: ... The current document
describes how to use the software to create a cluster of one or more co-operating METAMOD applications
(or METAMOD instances).

=head2 Data base

All the METAMOD instances in a cluster share a common data base. This data base is divided into the
following parts:

=over 17

=item B<Metadatabase>

SQL Database for Metadata

=item B<User database>

SQL Database for User administration

=item B<XML archive>

Metadata file archive based on XML

=item B<Data repository>

Archive of netCDF files

=back

One of the METAMOD applications in a cluster is responsible for the SQL databases. Initialization and
administration of the SQL databases are done through this application, which is called the I<base>
application.

Although the METAMOD instances in a cluster may operate on different servers, they must share a common
file system where the XML archive and the Data repository resides. Technically they may reside on
different file systems, but for each file, the file paths on the various servers must be the same.
Furthermore, for a smooth operation, the clocks on all the involved servers must be synchronized.

The SQL databases may reside on a separate server, different from any of the servers where
the METAMOD instances run.

=head2 METAMOD functional modules

The METAMOD software comprise a broad range of functionality. The software is divided into different
B<modules>, each representing a separate set of related functionality. One such module is the BASE module,
which is used in the base application described above. A METAMOD instance may use any combination of
modules. The only restriction is that one and only one application in a cluster must use the BASE
module.

The METAMOD software comprise the following modules:

=over 10

=item BASE

Responsibility for the SQL databases.

=item SEARCH

Web interface for searching a part of the database for metadata.

=item UPLOAD

Web interface and scripts for uploading (or registering) netCDF files and for editing metadata.

=item HARVEST

Module for harvesting metadata from internet servers offering OAI-PMH support.

=item PMH

OAI-PMH provider. See http://www.openarchives.org/.

=item THREDDS

Used for automatic building of THREDDS catalogs that may be utilized by a THREDDS Data Server to
access the data repository.

=back

=head2 Directory structure

On each server where METAMOD should run, the generic METAMOD software must be available in some directory.
In the description below, this directory is called the B<source> directory.

When deploying a METAMOD application, files in the source directory are copied to a B<target> directory.
The target directory is part of the runtime environment for the METAMOD application. Each application has
its own target directory, and the actual scripts and web generation tools are taken from the target
directory. The source directory has no role to play in the runtime environment.

In addition to the generic source directory, the METAMOD target directory is built from an
B<application source directory>. This directory contains configuration files, style sheets etc., and also
files regulating metadata requirements. An example application source directory is included in the generic
source directory (the C<app/example> subdirectory of the source directory).

The main subdirectories of the generic source directory are:

=over 10

=item base

Files only used in the BASE module

=item search

Files only used in the SEARCH module

=item upload

Files only used in the UPLOAD module

=item harvest

Files only used in the HARVEST module

=item pmh

Files only used in the PMH module

=item thredds

Files only used in the THREDDS module

=item common

Files used by several modules

=item catalyst

Perl Catalyst framework files used for web content generation inside several modules

=item app

Contains the example application source directory

=item docs

METAMOD documentation directory

=back

The module directories (base, search, upload, harvest, pmh, thredds) and also the common directory
(which in the following is implicitly included among the module directories),
all have a similar set of subdirectories:

=over

=item etc

=item scripts

=item htdocs

=item cgi-bin

=item lib

=item schema

=item init

=item userinit

=item staticdata

=back

A module directory will not contain all of these subdirectories. Some subdirectories are only
found in one module directory.

While deploying a METAMOD application, after the top level target directory is created, this directory
structure will be created directly beneath the top level target directory. The division between
modules will not be passed on to the target directory. Instead, a merging process will take place. Files
from different module directories, but contained in the same subdirectory, will all end up in the
same subdirectory in the target directory. For example: C<source/upload/etc/file1> and
C<source/base/etc/file2> will end up as C<target/etc/file1> and C<target/etc/file2>.

The application source directory will have the same structure as the target directory (or any of
the module directories). Not all the subdirectories listed above need to be present in the application
source directory.

In each of the module directories, and also in the application source directory there exists
a file C<filelist.txt> that contains a list of file names that should be
copied from that directory to the target directory. While copying the files, some files may be modified
as described in the B<Source file modification> paragraph below.

Since the target directory is populated from different sources, a possibility exist that the same target
file may correspond to several source files, each from a different module directory or from the
application source directory. In this case, a file in the application source directory have precedence.
Collisions like this between different module directories are not supposed to happen.

Since files in the application source directory have precedence, this fact can be used to replace any
file in any of the module directories with an application specific file. For the basic software (Perl
scripts etc.) this is not a recommended practice. But for typical configuration files, this is the
intended mechanism for tailoring a METAMOD instance to the users needs.

=head2 METAMOD configuration

=head3 master_config.txt

The application source directory contains a very important file, the B<master_config.txt> file. This file
governs how the target directory is built, and also provides runtime values for a set of configuration
variables.

The master_config.txt file is a text file containing lines as follows:

   VARNAME = VALUE

'VARNAME' must start from the first character on the line, and be all uppercase letters [A-Z], underscore
or digits. Any number of white space characters may separate 'VARNAME' and '=', and also '=' and
'VALUE'. 'VALUE' starts with the first non-whitespace character and ends with
the last non-whitespace character on the line. Additional lines may be
appended to 'VALUE' immediately after the initial 'VARNAME = ...' line. Such
lines must start with a space character. No whitespace are removed from such
appended lines.

Two variables are mandatory in master_config.txt:

   TARGET_DIRECTORY      This is the absolute path of the target directory, the
                         top level of the target directory tree.
   SOURCE_DIRECTORY      This is the absolute path of the generic source directory.

One important role for the master_config.txt file is to decide which modules should be included
in the application. For this purpose, the following variables are used:

   METAMODBASE_DIRECTORY
   METAMODSEARCH_DIRECTORY
   METAMODUPLOAD_DIRECTORY
   METAMODHARVEST_DIRECTORY
   METAMODPMH_DIRECTORY
   METAMODTHREDDS_DIRECTORY

If any of these variables are missing, the corresponding module will not be part
of the application. The value of these variables should be the absolute path of the subdirectory
in the generic source directory where the module is defined (i.e. the module directory).

A complete inventory of the variables that should be part of the master_config.txt file is found
in the C<app/example/master_config.txt> file in the generic source directory.

=head3 Metadata configuration

METAMOD is able to handle a large range of metadata frameworks. For metadata generated through the
UPLOAD module (by parsing netCDF files), METAMOD has defined its own XML format, called MM2. This
format has a similar structure as Dublin core; it is a flat structure with freely selected metadata
keywords. For each keyword one or more values may be found. Other metadata frameworks, like DIF or
ISO19115, are also accepted, and such frameworks will typically emerge when harvesting from other
metadata providers through OAI-PMH. While such frameworks (DIF, ISO19115) are hierarchical in nature,
a flattening of these structures takes place when they are imported to the SQL database and
presented through the METAMOD search interface.

The following configuration files regulate which metadata are imported to the SQL database and
available for search, how metadata imported by the HARVEST module are translated into the internal
flat structure used in the SQL database, and how metadata found in the uploaded netCDF files are
translated to MM2 XML files.

=over

=item staticdata/searchdata.xml

This XML file contains metadata vocabularies that are imported into the SQL database, and used
in the SEARCH module for setting up the interactive forms for web users searching the database.

=item etc/conf_digest_nc.xml

This XML file describes the parsing of netCDF files in the UPLOAD module. Specifically how
attributes and variable values in a netCDF file are translated into keyword - value pairs
and stored into an MM2 XML file. The C<conf_digest_nc.xml> file will contain rules regarding which
metadata are required in the netCDF files. The C<app/example/etc/conf_digest_nc.xml> file
represents a well commented example of such a file that can be used as a starting point for a
version tailored to specific needs.

=item etc/usererrors.conf

This file contain html templates that are used in error reports sent to data providers that have
uploaded netCDF files using the UPLOAD module. Each template corresponds to an error condition
defined in the etc/conf_digest_nc.xml file. An example file in the C<app/example/etc> directory
corresponds to the C<conf_digest_nc.xml> in the same directory.

=item XSLT

Files for translating from foreign metadata formats (... more text is needed)

=back

=head3 Stylesheets and other web configuration

METAMOD can be configured with custom texts and stylesheets. To modify the
styles of the application add the following directories to your application
directory and add all files that you want copy during the update_target.pl
process to filelist.txt.

=over

=item custom/templates

This directory contains the Template::Toolkit templates that you want to
override in your configuration. It is generally never a good idea to override
anything other than the C<custom.tt> file.

=item custom/static/css

This directory contains the CSS files that you want to override in your
configuration. It is generally never a good idea to override anything but the
C<custom.css> file in this folder.

=item custom/static/images

This folder contains the images that you use in your style configuration.

=back

=head3 Overriding texts

To override texts in the application you use the C<custom.tt> file.
C<custom.tt> is a file in C<Template::Toolkit> format.

The way it is used is that it re-defines the default texts found in
C<defaults.tt>.

For instance the following would re-define the HTML used for the header of the
application.

  [%

    # get a safe path to the header image that works in both Apache and outside of Apache
    SET header_image_url = c.uri_for('/static/images/logo.png');
    app.common.header_html = '<img src="' _ header_image_url _ '" />';

  %]

In the same way you can re-define any of the variables found in C<defaults.tt>

=head3 Overriding the CSS

In METAMOD you can override any of the CSS styles in the application using
C<custom.css> since this stylesheet will be the last one loaded by the
application. It is however wise to C<only> modify properties such as background
colors, foreground colors, borders and font size. Modifying the height, width,
padding, margins, display type etc. of elements can lead to the application not
displaying properly in different browsers. Also modifying these properties can
break between different versions of METAMOD.

The style for any element can be modified, but only a few are usually needed.
For an example of the common ones see C<app/example/custom/css/custom.css>

=head3 Path to images

One of the most common customisations are adding a logo image to the header and
the footer of the page. When adding images to the style it is important to get
the path to the image right.

=over

=item custom.tt

To get the path correct in the C<custom.tt> file you can use the following helper function.

 SET image_url = c.uri_for('/static/images/<your image name here>');

This makes a variable C<image_url> that contains the correct URL to the image file.

=item custom.css

To get the path correct in the C<custom.css> file you can use the following path.

  url("../images/aboutheader.gif");

as in

  background-image: url("../images/aboutheader.gif");

=back

=head2 Source file modification

While copying files from the source directories to the target directory, the files may be modified
according to the C<master_config.txt> file. Not all files will undergo such modification. Modification
can be suppressed by editing the  C<filelist.txt> file; by placing a "=" character as the first
character on the lines containing file names that should not undergo modification. The
following example from a C<filelist.txt> file shows how this is done:

   =scripts/createChildDatasets.pl
   =scripts/load_userbase.pl
   etc/standard_name.txt
   =etc/conf_digest_nc.xsd

Here only the C<etc/standard_name.txt> file will be modified.

The actual modification is done in the following way:

=over

=item *

In the file to be modified, all text strings matching C<[==VARNAME==]>, where C<VARNAME> is a
configuration variable defined in C<master_config.txt>, is substituted with the value assigned to
this variable in C<master_config.txt>.

=back

=head2 Deploying a METAMOD application

After the initial configuration has been completed, a number of scripts must be run before the
application is up and running. As these scripts will create files and directories that also are used
by the Apache runtime environment, it is important that
I<the user running these scripts is the same as the user running Apache>.

The first script should be run from the generic source directory. It will set up the target directory
and do some preparatory work:

   update_target.pl application_directory

The argument is the absolute or relative path of the application source directory, the
directory containing the master_config.txt file for the application. This script will do the
following tasks:

=over

=item *

Copy all files that are needed for the application, either from the generic source directory, or
from the application source directory. Only files used for modules included in the
master_config.txt file are copied. In each of the module directories only the files listed in
C<filelist.txt> are copied, and if a file is listed in C<filelist.txt> in the application source
directory, that file takes precedence, as explained above.
While copying the files, some files may be modified as described in
the B<Source file modification> paragraph above.

=item *

Install the Perl Catalyst framework onto the target directory. more text ...

=item *

Create an Apache configuration file for the application. more text ...

=back

After a successful run of the C<update_target.pl> script, the following script must be run from the
target directory:

   prepare_runtime_env.sh

This script will initialize a runtime directory used by the application for logging, temporary
files etc.

At this point, the deployment of the application is complete for all instances not using the BASE
module. For an application using the BASE module, a few steps remains:

As explained in the B<Data base> paragraph, several METAMOD applications may co-operate in a cluster,
and share a common data base. One of these applications must use the BASE module, and no other.
The last steps (described below) required for the base application must be done after the initial
steps (described above), for all applications in the cluster, are completed.

The two PostgreSQL databases used by the cluster must be initialized. Note that the two databases are
operated through two database users. The name of these users are found in the C<master_config.txt>
file as the value of PG_ADMIN_USER and PG_WEB_USER configuration variables. These users must be
defined in the PostgreSQL database environment before the database initialization scripts can be
run. The C<init/createusers.sh> script may be used for this purpose. It is only necessary to run this
script once for a PostgreSQL database environment.

The first SQL database initialization script will create the Meta database. This script must be run
from the C<init> subdirectory of the target directory:

   create_and_load_all.sh

This script will create the database, and load the static content of the database (taken from
C<staticdata/searchdata.xml>). You may check the output of this script in the
C<create_and_load_all.out> file in the same C<init> directory.

The next SQL database initialization script will create the User database. This script must be run
from the C<userinit> subdirectory of the target directory:

   run_createuserdb.sh

Note that I<this script must only be used during setup of a completely new METAMOD cluster>. If a
User database already exists, all data in the database will be lost. If this should happen, you must
recreate the database from a backup copy you hopefully have. But METAMOD will not by itself ensure
that such a backup exists.

This warning is only adequate for the C<run_createuserdb.sh> script. The other scripts in this
paragraph (C<update_target.pl>, C<prepare_runtime_env.sh>, C<create_and_load_all.sh>) may all be
used on an existing installation, without harming existing data. The C<create_and_load_all.sh> script
will take some time to complete, though. On an existing installation, all metadata in the database
will be loaded from the XML archive.

