=head1 Frequently Asked Questions

Back to L<Index|index>

=head2 Error messages

=head3 Transformation

=over 4

=item I'm getting the following error in the log:

    ERROR: no coordinate-systems with projection found, maybe you should try coordinate interpolation in CDMInterpolator.cc at line 488
    exception occured: CDMException: no coordinate-systems found

A: Your FIMEX version is out of date. Use 0.41 or later which supports selectVariables.

=back
