=head1 Frequently Asked Questions

=head2 Installation issues

=over 4

=item Q: Which other libraries must I install to run METAMOD?

A: When installing from a Debian package: I<NONE>. apt-get will automatically drag in
all predependencies, and all Perl modules are included in the Debian package.

If you want to run from source, you will find a list of required Debian dependency packages
in F<debian/control>. The Perl modules are included in Subversion, but must be built using
Carton as described in L<Installation|installation>.

=item Q: Where can I get some test data to populate the database for testing?

A: Set the config variable IMPORTDIRS before creating the databases. You can find
some sample datasets included in F<test/xmlinput>.

=item Q: I just found a config variable, but it doesn't seem to be set in either master_config or default_config?

A: METAMOD computes some variables automatically. For a list of current values, run

  $ lsconf --nocustom --nodefault

=back

=head2 Error messages

=head3 Installation

=over 4

=item Q: I get the following error message when trying to run sudo:

  sudo: sorry, you are not allowed to set the following environment variables: PERL5LIB

A: You seem to be having restricted full sudo rights. See L<deploying> for more info.

=back

=head3 Visualization

=over 4

=item Q: When I open the WMS client, no data layers are rendered on the map until I click on something in the layer selector

A: You must specify at least one layer in wmsinfo, otherwise all layers will be set to hidden (collapsed).


=item Q: The WMS client fails to show any images, and Log4JS reports the following error:

    FATAL - Invalid GetMapContext: TypeError: maxExtent is null

A: This rather cryptic error is OpenLayers complaining about having no background
layer. Check that you have a background map available in the specified projection.

=back

=head3 Transformation

=over 4

=item Q: I'm getting the following error in the log:

    ERROR: no coordinate-systems with projection found, maybe you should try coordinate interpolation in CDMInterpolator.cc at line 488
    exception occured: CDMException: no coordinate-systems found

A: Your FIMEX version is out of date. Use 0.41 or later which supports selectVariables.

=back

=head3 PostGIS

=over 4

=item Q: I'm getting the following error in the log:

  SELECT AddGeometryColumn('public', 'dataset_location', 'geom_3995', 3995, 'GEOMETRY', 2);
  ERROR:  AddGeometryColumns() - invalid SRID

A: Check that the projections specified in SRID_ID_COLUMNS are available in the database:

  test_metadata=# select auth_srid from spatial_ref_sys where auth_name='EPSG' and auth_srid in(93995, 93031, 3995, 3031, 4326);
   auth_srid
  -----------
        4326
        3031
        3995
  (3 rows)

If some of them are missing, make sure PostGIS is correctly installed and restart the PostgreSQL service:

  $ sudo apt-get install postgis postgresql-9.1-postgis
  $ sudo service postgresql restart

=back

=head2 Performance

=head3 Web server setup

=over 4

=item Q: Help! GoogleBot seems to bring down my site!

A: You need to block parts of the search interface to robots. METAMOD generates a
robots.txt dynamically on /metamod/robots.txt and aliases this in the Apache configuration.

If you already have an existing robots.txt file you should disable the alias
and copy the relevant lines into your own file.

Note that if you have a static welcome page served by Apache for the site,
it is important that you link to C</metamod/> and not C</metamod/search>,
otherwise robots will not index your datasets.

=item Q: Metamod/Catalyst/Apache suddenly stopped, and I can't find it when running C<ps aux>

Check that your server hasn't run out of swap. If this happens, the Linux kernel
will start killing processes arbitrarily. This is very hard to handle locally since
you won't be able to start new processes, instead you must rely on external monitoring tools
like Nagios.

=back
