=head1 METAMOD documentation

METAMOD 2.x is a portal solution providing Discovery, Access and Retrieve
functionality for scientific datasets along with tools for metadata handling
etc. It allows for automatical and manual DAR Metadata creation. The Metadata
can be converted to different formats and exposed using different
search-interfaces, i.e. ISO23950 and OAI-PM. METAMOD 2.x has been designed to be
easily integratable with L<OpENDAP|http://opendap.org/> or ftp data-servers,
i.e. L<THREDDS|http://www.unidata.ucar.edu/projects/THREDDS/> and allows
data-upload through FTP and HTTP interfaces.

=over 4

=item L<Overview|overview>

The basic principles behind METAMOD

=item L<Installation|installation>

How to get the METAMOD base software

=item L<Upgrading|upgrade/index>

Upgrading from an older version of METAMOD

=item L<Deployment|deploying>

Setting up a METAMOD application

=item L<Configuration|configuration>

Configuration details and custom templates

=item L<FAQ|faq>

Frequently asked questions (for any definition of frequency)

=item L<Datamodel|datamodel>

The data-model and the data-flow within METAMOD2

=item L<Metadata extraction|metadata_extraction>

Import and upload description

=back

METAMOD is copyright L<The Norwegian Meteorological Institute|http://met.no>.
METAMOD is free software, released under the L<GNU General Public License, version 2|http://www.gnu.org/licenses/gpl-2.0.html>.
