=head1 METAMOD software installation

Back to L<Index|index>

=head2 Introduction

This describes how to install the METAMOD base software on a Linux server.
No services will be available until you configure and set up a METAMOD instance
(see L<Deploying a METAMOD application|deploying>).

METAMOD is developed, tested and used on Ubuntu LTS servers (Hardy, Lucid).
Debian packages are provided regularly for easy installation and upgrading.
Installation from source is also possible, but requires much more work (at
least for dependency libraries).

=head2 Required software

=over 4

=item PostgreSQL database system

Tested on version 8.3 and 8.4. If running a local database you need the PostgreSQL
server, otherwise only the client is required.

=item Apache 2.x web server

With mod_proxy installed (sudo a2enmod proxy)

=item libxml and libxslt library

From xmlsoft.org

=item Proj4 library

L<http://proj.maptools.org>

=item NetCDF software 3.5 or later

libnetcdf, ncdump and ncgen

=back

=head2 Installation from Debian packages

This requires you have sufficient sudo privileges to install packages and
add repositories.

=head3 Adding the met.no package repository

B<Note: Currently this repo is not available outside met.no. External users must
download and install packages manually as described below.>

Add the corresponding lines to your /etc/apt/sources.list depending on your
version of Ubuntu:

  # for lucid
  deb http://repo.met.no/met.no lucid main contrib
  deb-src http://repo.met.no/met.no lucid main contrib

  # for hardy
  deb http://repo.met.no/met.no hardy main contrib
  deb-src http://repo.met.no/met.no hardy main contrib

If you want to run development versions (recommended), also add:

  # for lucid
  deb http://repo.met.no/devel lucid main contrib
  deb-src http://repo.met.no/devel lucid main contrib

  # for hardy
  deb http://repo.met.no/devel hardy main contrib
  deb-src http://repo.met.no/devel hardy main contrib

=head3 Installing METAMOD and dependencies via apt

  $ sudo apt-get install metno-perl-webdev-ver1
  $ sudo apt-get install metno-metamod-2.12

=head3 Installing packages manually

Alternately you may download the .deb files and install manually. These may be found
on the following sites:

=over 4

=item L<https://wiki.met.no/metamod/download>

=item L<http://repo.met.no/devel/dists/lucid/main/binary-all/web/>

=back

Installation is done using a GUI packet manager or via command line:

  $ sudo dpkg -i metno-metamod-2.12_2.12.0-2_all.deb

where 2.12.0-2 is the latest version in the repository.

=head2 Installation from source

=head3 Perl module dependencies

We really do not recommend installing the 350 required Perl modules (plus an
additional baker's dozen of compiled C libraries) from CPAN unless you're really
hardcore (or desperate). If you can, install the metno-perl-webdev-ver1 Debian
package as specified above.

A complete list of Perl module dependencies (as per 2012-01-31) can be found in
F<metamod-deps.txt>; this can be used as a source for scripting.
At some point there might be a METAMOD::Bundle module, but don't hold your breath.
Note however that some modules will not pass all tests and must be force
installed; this includes but is not limited to the following CPAN modules:

=over 4

=item Taint

=item Class::MOP

=item Module::Install

=item DBIx::Class

=back

=head3 Checking out the METAMOD source

Assuming you have the dependencies sorted out, installing METAMOD from source
is a piece of cake. All you need is to check out the code from Subversion
into a suitable directory. No special privileges are required (yet).

  $ mkdir metamod
  $ cd metamod
  $ svn co https://svn.met.no/metamod/trunk

=head3 Conclusion

You will now have the necessary software installed, however it will not do anything
until you configure and set up a METAMOD application. See L<configuration> and
L<deploying> for further instructions.
