=head1 System administration

=head2 Configuration

Keeping track of all necessary config variables in master_config.txt has
often been the most time-consuming part of setting up a new installation.
The C<lsconf> tool has been developed to assist with this.
Here are some examples (using virtualenv):

Checking if your configuration is valid:

    $ lsconf --check
    # Testing config in /home/anton/metamod/mysite
    ok 1 - config directory found
    ok 2 - WEBRUN_DIRECTORY is writable: /home/anton/metamod/webrun
    [...]
    ok 37 - OPERATOR_EMAIL is a valid email address
    1..37

How to get nice color output when using a pager:

    $ lsconf --color | less -R

=head2 Dataset administration

=head3 Debugging

If you want to check dataset metadata like XML, WMS, WMC, OPeNDAP etc, you can
enable debug functions in the web search interface by adding I<&debug=1>
to the end of the query string (prefixed by "?" if not set):

  http://example.com/metamod/search/page/1/result?debug=1

You can also use the command line utility C<lsds> (see below):

  $ lsds --wms                              # list datasets with wmsinfo and test if valid
  $ lsds --projectioninfo                   # list datasets with projectioninfo
  $ lsds --xmlfile                          # list paths to xml files

=head3 virtualenv

This handy utility, lifted from Ruby and Python, creates a small shell script
which can be sourced to set all necessary environment variables like
PERL5LIB and METAMOD_MASTER_CONFIG so you won't have to repeat that for
every shell command. It also puts most METAMOD commands in your PATH for
easy access.

    $ /opt/metno-metamod-2.13/virtualenv.pl metamod/config
    $  . metamod/config/bin/activate
    (config)$ lsconf
    (config)$ lsds
    (config)$ metamodweb_server -dr

If for some reason you don't have write permissions to the config directory,
you can specify another path to write the files:

    $ /opt/metno-metamod-2.13/virtualenv.pl metamod/config /home/anton

To reset the environment:

    $  deactivate

=head3 lsds

A quick way to query the metadata database without using the web interface
is to use the C<lsds> command line tool. This will list datasets with
as much info as can be found in the database. Some search facilities are available,
but most parameters from the web interface has not been implemented yet.

Some examples of use:

  $ lsds 828 829 830 831                    # list datasets by id
  $ lsds --full NORMAP/metno-sstana05-V2    # show metadata by name
  $ lsds -m dataref_OPENDAP                 # list datasets containing a keyword
  $ lsds -p freetext=ice_conc               # search by free text parameter
  $ lsds -c -p 'freetext=ice AND arctic'    # boolean search, only show count
  $ lsds --wms                              # list datasets with wmsinfo and test if valid
  $ lsds --projectioninfo                   # list datasets with projectioninfo
  $ lsds --xmlfile                          # list paths to xml files

